org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.21
forge_version_range=[47.4,)
loader_version_range=[47,)

mod_id=anviltweaks
mod_name=敌对神经网络自动获取生物掉落物
mod_license=MIT
mod_version=1.0
mod_group_id=com.tfar.anviltweaks
mod_authors=tfar, Antigravity

mapping_channel=official
mapping_version=1.20.1
