plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '6.0.+'
    id 'org.spongepowered.mixin' version '0.7+'
}

version = '1.0.0'
group = 'com.antigravity.debuglogger'
archivesBaseName = 'DebugLogger'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                debuglogger {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, 'mixins.debuglogger.refmap.json'
    config 'mixins.debuglogger.json'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.13'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly fileTree(dir: 'D:/Plain Craft Launcher 2/.minecraft/versions/勇者之章Ⅲ v3.12.15/mods', include: ['*.jar'])
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "debuglogger",
                "Specification-Vendor"    : "antigravity",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "antigravity",
                "MixinConfigs"            : "mixins.debuglogger.json"
        ])
    }
}
